### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by malah-code**
This is some enhancements, you can take it all or just take some of new features, if applicable.
This is first time I do enhancements on Github project, I don't expect to be easy to accept that pull request, but please let me know.
Below list of changes /enhancements  summary :
-Use DB with SQLITE as main storage of the application. this will reduce the dependancy of files, and increase the number of features that we have with SQLITE that we can add it to the application later easily, like Sorting/Filer/Grouping/relation with other tables like categories and rating, add more station metadata, and many more.
	-adding more metadata to stations (currently no way to change all metadata throw UI, we can only import xml with all metadata of channel, we may add editing later in next versions).
	-new station rating modules (currently it's local rating only, not sync to central rating, may be later in next versions)
	-Using Facebook fresco image viewer (SimpleDraweeView) with it's great loading features
	-Apply Material design components and transitions
	-Integrate with Firebase compoenents 
			-Authentication
			-Analytics
	-Add login by Google account function (currently nothing happend after login, but in the next versions we can connect user by ID and save his data to cloud for example, and many more.)
	
Thank you,

### CODE REVIEW

**Comment by y20k** [comment]
Hi @malah-code,

I was bit overwhelmed at first when I looked through the suggested changes to be honest. The result is huge step forward for Transistor. The app looks very promising 👍. But wait... There is is "but",

I have (in lack of a better word) a vision for Transistor: It should always stay very simple and straight forward. Just like the old transistor radios back in the days used to be.



_Image Source: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:GraetzSuperPage67_&#40;1&#41;.JPG)_

Many of the changes you made steer the app in another direction, which I like in general - but they change Transistor to a degree which I am not comfortable with. 

I think you are a talented coder and you have a beautiful vision for a free radio app. And while there are a lot of radio apps out there, there is definitely still a need for a good free alternative to the slow and sluggish no.1 (= TuneIn). The old Transistor here will always be an app that fills a very special niche. Your app has the potential for a bigger audience. I would say: Go for it! And while you are at it you could consider to team up with @segler-alex (see #94). He has a great free and open radio directory.

I hope that you understand me and that you are not disappointed. Looking at your fork of Transistor at GitHub gives me the impression that you were maybe planning to go your own way anyway 😄 which is great. (In this case my only request would be. Please consider changing the the name of your app and give it a different icon.)

PS. In the unlikely case that you now think: "This @y20k guy is an idiot. I put so much work in this!! 😞" (I really hope that you don't think that.) Anyway. My only defense would be: I have a [CONTRIBUTE.md](https://github.com/y20k/transistor/blob/master/CONTRIBUTE.md) that has a passage about submitting code.

> Help is very welcome. Be it in the form of code, or artwork, or enhancements to the website, or tutorial videos, or whatever. But please suggest new features or enhancements in advance on the Issue Tracker before implementing them.

**Comment by malah-code** [comment]
@y20k , I totally respect and understand your point and your suggestion. and sorry I didn't read CONTRIBUTE.md before I started my changes :) .

Mostly, I'll go my own way by copy to new project (or detach the fork) and will change name and logo of course :smile: . and I may find some other developers shares my ideas to contribute.

It was honor communicating with such great developer like you, and wish you follow my project and contribute with advises.
Thank you,

**Comment by Nathoufresh** [comment]
@malah-code , have you forked this project ? I would be happy to see it 😊

**Comment by malah-code** [comment]
Hi,
It's became 2 project, buy I didn't work on them since one year ago


https://github.com/malah-code/Android-Open-Radio

https://github.com/malah-code/Open-Quran-Radio

Hope that help,

Malah

**Pull request closed without merging**
