### PR TITLE
Do not kill notification if network is disconnected or playback error occurred

### PR DESCRIPTION
**Pull request by pelya**

### CODE REVIEW

**Comment by y20k** [comment]
Hey thanks!! I do not have my Dev box at hand (= short vacation). I will look into it next week. I did not know that that was an issue.

**Comment by pelya** [comment]
I would rather like Transistor to re-attempt to connect to the radio
station each 5 seconds in case of any network error, until I press 'Stop'
button myself, but now at least I can resume playback from the lock screen.
Android MediaPlayer does this by itself to some extent, at least on my
phone - it switches between WiFi and 3G depending on which is currently
available, but it stops trying after 10 seconds of bad network.

**Comment by pelya** [comment]
To reproduce the bug: launch playback, then disable WiFi and 3G, wait 10
seconds, and the notification disappears.

**Comment by y20k** [comment]
A short note aside: 

From time to time I Transistor stops audio playback. This happens rarely and only after 45+ minutes (related to #88). I have no idea what's wrong and as far as I see there is no feedback from mediaplayer that the app could pick up to start a reconnect.

Do you experience that too? Any idea what to do? Do I miss anything? 

Maybe your metadata proxy could detect a connection problem.

**Comment by pelya** [comment]
I am not usually running a connection that long. Could be your radio
station terminating connection after a fixed time, people configure them
sometimes to drop 'inactive' users this way, but most media players simply
reconnect again.

**Comment by y20k** [comment]
Hi @pelya ,

First: Thank you for the pull request. Leaving up the notification is **definitely** a better user experience in case of a connection error!

> I would rather like Transistor to re-attempt to connect to the radio station each 5 seconds in case of any network error

I did add a simple reconnect. (see: [`PlayerService.java`](https://github.com/y20k/transistor/blob/4b8f96a757ff41c99345dabf759459b176840123/app/src/main/java/org/y20k/transistor/PlayerService.java#L346)). I need to test if it actually works.

> it stops trying after 10 seconds of bad network.

Do you have a suggestion on how to simulate "bad network"?

**Comment by pelya** [comment]
"bad network" on my device happens when I turn off WiFi and 3G in Android
settings.

If you want to simulate bad network in a more professional way, you can
unplug network cable from your WiFi router, or enable WiFi hotspot on
another phone, connect to that other phone via WiFi, and then disable 3G on
it.

**Pull request merged**
