### PR TITLE
extend notification

### PR DESCRIPTION
**Pull request by flashback2k14**
Hello,
today i have noticed that, if I click the "clear all notification" button that transistor app / notification closes also. I think this behaviour is not so good. I really like this app. I have deleted TuneIn Radio for your app, because all I need is streaming a radio channel. no more no less. :-) I hope you like my changes. :-)

I change the following:
- notification: add buttons to play, pause and stop stream
- notification: open the app on stream name click
- implement pause functionality
- add new drawables for play, pause and stop
- show some toast to inform the user
- simplify returns in Station.java and StationDownloader.java
- screenshot:
screenshot

### CODE REVIEW

**Comment by y20k** [comment]
Oh wow. Thank you! First a note: I am a bit overwhelmed with all the feedback Transistor got in the last couple of weeks. Your pull request is kind of a culmination for all of that.

But there are some problems. I am hesitant to write that because I think it is so kind of you not only to request a feature, but also to offer the solution right away. But in a sense this is the problem.

When designing the app in the first place I did decide against a several features, among them: pause, next and previous buttons. I just wanted to have one big button for play/stop. Introducing a pause feature in the expanded notification is therefore a problem. The functionality is not mirrored in the main app UI. There is still just one big button. 

Introducing "pause" into the main UI is not an option. It would introduce the need to implement an element where one can see the state of the player. MP3 players solve that by adding a miniplayer at the bottom of the screen. I do not like the concept of a mini player (at least for Transistor). That is basically the reason why I did decide against a pause feature in the first place.

That brings me back to my fist comment. "Being overwhelmed." I did not have a guide or policy on how to contribute to this project before. So you could not have known in advance that a new features MUST be discussed before implemented. First thing I did this morning is put up a rudimentary "how to" document ([CONTRIBUTE.md](https://github.com/y20k/transistor/blob/master/CONTRIBUTE.md)). Obviously that does not help in this case.

I am very(!) sorry to disappoint you. I cannot merge this pull request as it is now. The only thing I can do is go through your changes line by line and add those that do not alter the UI.

**Comment by flashback2k14** [comment]
hey,
no problem. i understand your points and problems. it's your app and you decide want you want or what the app needs.

**Comment by y20k** [comment]
Okay. I am glad to hear that. If you ever come to Stuttgart... I'll buy you a beer for compensation. ^o^

**Comment by flashback2k14** [comment]
hehe. Or if you come to Leipzig, you can buy me the beer, too. ;-P

**Comment by meonwax** [comment]
I really like the feature but i also agree with the doubts about the UI integration.

Nevertheless, your code showed me a nice utilization of vector icons for the buttons.
@flashback2k14: Have you created them by hand or is there a public available source?

**Comment by flashback2k14** [comment]
i have used the vector assets provided by google. that's the material design icons
as

**Comment by meonwax** [comment]
Wow thanks!
I didn't know that option exists in Android Studio. I'm still used to work with the Eclipse ADT plugin.

**Comment by flashback2k14** [comment]
I think you should switch to AS, because Google doesn't maintain ADT anymore.

**Comment by meonwax** [comment]
> I think you should switch to AS, because Google doesn't maintain ADT anymore.

Yes i already switched, but i'm not pretty familiar with it.

So back to topic:
@y20k: Even though you will not merge this PR fully, you should think of merging some parts of it:
- notification: open the app on stream name click
- change the swipe-to-stop behavior in favor of adding a stop button because this way, clearing all notifications won't stop the stream

**Comment by y20k** [comment]
Hi @meonwax, 

A tap on the notification brings you to the player screen already. At least it should do so. But you are right, I should consider adding a stop button. I like the swipe to stop feature though. But that "dismiss all notifications" stops playback sucks.

**Pull request closed without merging**
