### PR TITLE
When playlist has several streams show selection dialog to the user

### PR DESCRIPTION
**Pull request by pelya**
Almost all radio stations have several streams in the playlist, usually mirrors, but sometimes with different bitrate or codec. The worst abuser is this station, which has separate stream with different music in the same playlist: https://dnbradio.com/hi.pls
This patch will show a simple popup dialog with all stations from the playlist, and user can select one.

One bug that I've noticed is adding two streams from the same playlist makes Transistor save them into the same file on disk, so the next time it starts, it loses one stream from the station list. But this can be reproduced even without the patch, if two different radio stations have a playlist file named 'listen.pls' for example, it will be overwritten if you add both.

### CODE REVIEW

**Comment by y20k** [comment]
Hi @pelya,

Thanks for the pull request. Stream-selection is a very good feature. 

One question: does the feature work with multi-stream m3u/pls that have just URLs - and no Names?

And about the implementation details. I think I need to take the code apart a bit to fit in the project structure. E.g. I will probably put the dialog into a separate helper class.

Nontheless. Great work! And thanks for the contribution.

**Comment by pelya** [comment]
Yes, it should work on nameless streams, it will then show only URLs.

On 2 Mar 2018 10:49 am, "y20k" <notifications@github.com> wrote:

Hi @pelya <https://github.com/pelya>,

Thanks for the pull request. Stream-selection is a very good feature.

One question: does the feature work with multi-stream m3u/pls that have
just URLs - and no Names?

And about the implementation details. I think I need to take the code apart
a bit to fit in the project structure. E.g. I will probably put the dialog
into a separate helper class.

Nontheless. Great work! And thanks for the contribution.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/y20k/transistor/pull/175#issuecomment-369859246>, or mute
the thread

**Comment by y20k** [comment]
Hi @pelya , I did incorporate the code you requested to pull into the app, Since I wanted the new code to fit in better with the rest of the app. I adapted the code manually. That does not implicate any judgement whatsoever! The code works great. And I am very thankful. Best regards. (I am closing the request)

**Comment by pelya** [comment]
Cool, thank you.

**Pull request closed without merging**
