### PR TITLE
Add widgets

### PR DESCRIPTION
**Pull request by grrosminet**
this will add widgets of different sizes presenting known radios in a grid view
tapping on a radio icon will start playing it, tapping again will stop it.

### CODE REVIEW

**Comment by y20k** [comment]
Hi @grrosminet ,

Thank you for this pull request. I just checked out your branch and started it on an Emulator. I need to do some testing with it.

A quick response: Judging from the amount of code this pull request presents a huge pile of work on your side. I did not expect that. In [CONTRIBUTING.md](https://github.com/y20k/transistor/blob/master/CONTRIBUTING.md) I am asking anyone, who would like to donate his/her time to the project, to contact me first. That is because I am a bit afraid that there is always a not so small possibility that I reject a pull request.

In this case: We should probably have talked about the goal of adding widgets, then about possible designs and since Transistor has always been about simplicity about the limits and boundaries of a feature

Transistor has a feature where you can put selected stations on the home screen. In its current form the widgets you created duplicate the existing feature in a way. I think a step forwards feature-wise would be a widget that can control playback. Maybe just for a single station. Such a widget could be very small - station icon, station name, play/stop button.

Anyway this is just a very hot take on your work. I will need to test this a bit more. I owe you that, since this has been a lot of work.

**Comment by y20k** [comment]
a quick screenshot of the 4x3 widget running on an emulator
Screenshot_1581369194

**Comment by grrosminet** [comment]
Hi,
I have tried to use the shortcut you provide. It's not applicable to my use case :
- it brings the app to the front
- you can only add shortcut to main launcher desktop.
 In my case I want to add widgets / shortcuts to my car deck app and don't want to open the app as I'll be driving. So widgets is a nice solution.
so don't worry for the time spent (only 4 hours) : it won't be lost if you can't include it inside your project : I will use the fork. 🙂

**Comment by grrosminet** [comment]
Hi @y20k , 
I have polished my submission :
* radio icons with name bellow, allways square
widget_4c
* small widget 1x1 as you described it
widget_1c
* fixed PlayerService launch once it have been destroyed
* tested (for real)

Hope it'll please you :-)

**Comment by y20k** [comment]
Hi @grrosminet ,

I did some more testing of the widgets. Including your latest additions from today. I am still worried about all the work you are putting in here. The app currently crashes when started on Android 4.4, but aside from that the basic functionality is there: Icons, Playback Indicator, Station Names, Playback.

One of improvements this would bring over the current solution (Home Screen shortcuts) is: The widget does not bring the app in the foreground and it can toggle play/pause. But I guess that can be also archived with a few tweaks to the ShortcutHelper.

Looking at the user interface,  I think there is still a lot of work to do until this feature really is production-ready.  I think it is not worth it to put too much work into this feature. And I would just stay with the fork. I am planning to rewrite the whole app in the later half of 2020 (Kotlin). I will probably re-design some of the interface, too.

BUT: If you really really want this feature to be in Transistor we should schedule a chat or videocall where we can discuss what still needs to be done in the UI.

Screenshot_1581693184

**Comment by grrosminet** [comment]
Hi,

I'm not sure you can update shortcuts as fast as widgets to add or remove play-back indicator. 
On my opinion, a large widget with all radio stations is interesting as it won't require updates from user. It's a complementary solution. 
Yes, I really need theese widgets : i'm working on a car dock and want the user (me) to be free to choose what he want to see. I have installed transistor a few monrhs ago and never really used it. Now with widgets integrated inside my dock I use it every day.
But don't worry about that : I can continue using my fork 🙂

**Comment by grrosminet** [comment]
Hi,

I'm using Oreo (lvl 26) on my phone. I never had any crash using prev/next on bluetooth headset, but it did ... nothing !

So I have looked into PlayerService and seen you onSkipToNext/Previous but never seen the log trace. So I googled, again and again and found a mention of onMediaButtonEvent in the google doc. As I have been able to enter inside this, it was "_my_" solution (the one that fix my problem in my special case).
If you look into the super of onMediaButtonEvent you'll see that it is neutralized since API level 27, so maybe BT prev/next works out of the box since this API level, and maybe _my_ solution breaks it all ! As I mentioned in the comment of [Issue 227](https://github.com/y20k/transistor/issues/227) this will require a lot of testing

**Pull request closed without merging**
