### PR TITLE
Add Ukrainian language

### PR DESCRIPTION
**Pull request by burunduk**
Please, add Ukrainian language.

### CODE REVIEW

**Comment by y20k** [comment]
Wow. Thank you! May I add your GitHub handle to the [authors](https://github.com/y20k/transistor/blob/master/AUTHORS.md) list? 
If you agree, I would like to forward you future pull request for the Ukranian translation. You would be somewhat in charge, since I cannot decide if a proposed change is correct.

**Comment by burunduk** [comment]
Yes I agree.
Thank you for Transistor!

**Comment by y20k** [comment]
Great! Thanks again.

**Comment by y20k** [comment]
Hey burunduk, 
I opened an internal Issue (#23) here to keep translators up-to-date about plans for new releases. You maybe want to subscribe to the Issue.
Best wishes

**Pull request merged**
