### PR TITLE
UX tweaks for screen reader users

### PR DESCRIPTION
**Pull request by pvagner**
Thank you very very much for such a great app. It's minimalistic but perfectly serves the purpose.
It is fully accessible since I have discovered it.
However I have added some little incremental improvements related to accessibility. Yes, I've seen #190.
I have tried to explain the changes in the commit messages but anyway here is a summary.

It's amazing all widgets are clearly labelled however some of the original descriptions were too verbose. For example when touching station icon on the player sheet, Talkback reported "Station icon Image". After I have tweaked it it just says "image". The same goes for buttons, dropdowns and other actionable widgets. If possible I'd suggest to avoid describing the widget type as that's already available to the accessibility services through other APIs.
Anoter important thing to consider is that contentDescription is an alternative content for non-textual content. Some accessibility services may prefer content description over the actual text. So I have removed a few content descriptions to fallback on the text where the text makes more sense than the content description.
I have removed a few more content descriptions because setting content description for non actionable decorative elements only creates confusion for screen reader users. For example touching an entry named "blah fm" in the list of stations caused Talkback to report "station icon Blah FM" that station icon is not needed in such a case. In contrast playing indicator is there for a reason.
Also if you are using images to signal UI state changes it's a good idea to update corresponding content description as well. I have added dynamic content description to the playback button.

The changes are minor, I just wanted to explain why I think they are appropriate as accessibility is a huge topic.

I have tested this on a real device with Talkback running.

Also if related issues will arise, I'm happy to continue improving this.

Thanks once again

Greetings

Peter

### CODE REVIEW

**Comment by y20k** [comment]
Hi @pvagner, 

Thanks for the excellent pull request and your explanation. That is very helpful not only for Transistor but also for other projects I am working on. I will wait a couple of days before publishing it. I want to see if translations from Weblate come in for this.

**Comment by y20k** [comment]
Looking over the content descriptions, I think some maybe still too verbose for day to day app usage via a screen reader. (I never really thought about that). If you agree, feel free to change even more content description strings.

**Comment by pvagner** [comment]
Hello,

Huge thanks for accepting my changes and another round of thanks for the positive comments.

While translating I managed to review all the strings.
I think a few of them may not be used at all if I am not mistaken.
Related to over verbosity I haven't noticed issues when using the app during a few days.
If it's okay, I will try to fix possible issues as I discover them or anyone points me to them.
One more thing I have noticed but I haven't investigated so far is that when renaming a station, the old content description is preserved both in the list and in the player sheet.
I'd like to remove content descriptions for the widgets which do already have good text even with no accessibility considerations.
I agree that waiting a few days or weeks for updated translations is a good idea.
In a few days I will try to sort at least the rename station issue.

Thanks once again

Greetings

Peter

**Comment by pvagner** [comment]
Ooops, I don't want to sound rude however the way you have tweaked all the translation strings files is not very good idea I think.

You have added these two lines to all the files:
```
    <string name="descr_playback_button_play">Play</string>
    <string name="descr_playback_button_stop">Stop</string>
```

This way these strings won't be suggested for action on weblate because they are already translated although they carry the original english translation not the target language translation.
Or are you manually comunicating new translation changes to the translators?
I think this is unnecessary and weblate does this fine with no changes to the translation files.
Can you consider reverting this?

**Comment by y20k** [comment]
I have been doing this for a while. I cannot remember for sure why :-) As far as I remember, Android Studio,  Play Store, or F-Droid, demanded that all translations are complete.

**Comment by y20k** [comment]
I will try and check if it was Android Studio. If so there must be fix I can apply to persuade it to sign and compile a release APK with missing translations.

**Comment by pvagner** [comment]
You are looking for this added into the app/build.gradle
```
    lintOptions {
        warning 'MissingTranslation'
    }
```

**Comment by y20k** [comment]
Okay, thanks. That sounds like a simple fix 😄.

I will try this when it's time to release the next version. First I will remove the English strings from other languages and see if it compiles correctly. If that works the next step is to publish a new release on GitHub only and make sure that F-Droid has no problems picking it up. If that works, I will publish the new version on Google Play.

**Comment by y20k** [comment]
Just as test I did not completely remove the line line containing the translation. I just emptied the XML tag. 

Before
`<string name="descr_playback_button_play">Play</string>`

After
`<string name="descr_playback_button_play"></string>`

I want to see how Weblate handles that. If that is not a problem I would prefer this solution, because it helps me to keep the `string.xml` files structured in a way I like. The problem otherwise is that Weblate just adds newly translated strings at the end of the file - and I like to group/organize the strings a bit.

**Comment by pvagner** [comment]
Thank you, that is working fine and weblate is suggesting to translate the strings.
I think this will help translators to do their job even better since they will not have to hunt for strings where the source and translation are the same because it needs work or because it should stay like that.
I've just updated slovak in the process.

Thank you again.

**Pull request merged**
