### PR TITLE
This should fix incorrect StationID in notification

### PR DESCRIPTION
**Pull request by pelya**

### CODE REVIEW

**Comment by y20k** [comment]
Thanks. That was pretty quick, :+1:  I forgot to mention why the stationID-thing was a problem: Tapping on the notification did not work properly before. That is now fixed. Nice. 

Have a nice weekend.

**Comment by y20k** [comment]
Hey @pelya,

I put the metadata extraction code you wrote into a new helper class (see [commit](https://github.com/y20k/transistor/commit/0d3774d552f2be26435a76c80277ddeae1cd43a1)). I hope that is okay for you! That makes the app a bit more modular. Changes in the player service will not affect the metadata helper and vice versa.

The noticeable change is probably: `closeShoutcastProxyConnection` is now `public`

I am right now wiring up the station metadata to the Now Playing screen.

Best wishes

**Comment by pelya** [comment]
Yes it's okay. I don't care so much about implementation, but rather about
the functionality it provides.

**Comment by y20k** [comment]
:+1:

**Pull request merged**
